<?php

$plugin = array(
  'title' => t('Section template'),
  'theme' => 'atp_section',
  'icon' => 'atp-section.png',
  'category' => t('ATP'),
  'admin css' => '../../../css/layouts.css',
  'css' => '../../../css/layouts.css',
  'regions' => array(
    'row1' => t('First row'),
    'row2' => t('Second row'),
    'row3' => t('Third row'),
    'row4' => t('Fourth row'),
    'row5' => t('Fifth row'),
  ),
);