<?php
/**
 * @file
 * Code for the ATP news.
 */

define('ATP_NEWS_TID_NEWS_CATEGORIES', 1);

include_once 'atp_news.features.inc';

/**
 * Implements hook_ctools_plugin_directory()
 */
function atp_news_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/content_types';
  }
  if ($module == 'ctools' && $plugin == 'contexts') {
    return 'plugins/contexts';
  }
}

function atp_news_get_news_categories_vocab_id() {
  $vid = &drupal_static(__FUNCTION__);
  if (!isset($vid)) {
    $vocab_categories = taxonomy_vocabulary_machine_name_load('news_categories');
    $vid = $vocab_categories->vid;
  }
  return $vid;
}
/**
 * An array of possible news list types.
 *
 * @return array
 *   List types.
 */
function atp_news_list_type_options() {
  return array(
    'fixed_categories' => array(
      'title' => t('Fixed categories'),
      'description' => t('News list with fixed categories.'),
    ),
    'filtered' => array(
      'title' => t('Filtered'),
      'description' => t('News list with category filter options.'),
    ),
  );
}