<?php
/**
 * @file
 * Code for the ATP news.
 */

define('ATP_NEWS_TID_NEWS_CATEGORIES', 1);

include_once 'atp_news.features.inc';

/**
 * Implements hook_views_api().
 */
//function atp_news_views_api() {
//  return array(
//    'api' => 3,
//  );
//}

/**
 * Implements hook_ctools_plugin_directory()
 */
function atp_news_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/content_types';
  }
}
