<?php

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function atp_toolbar_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}


/**
 * Implements hook_theme.
 */
function atp_toolbar_theme($existing, $type, $theme, $path) {
  $tpl_path = drupal_get_path('module', 'atp_toolbar') . '/tpl';
  $themes = array(
    'toolbar' => array(
      'template' => 'toolbar',
      'variables' => array(),
      'path' => $tpl_path,
     ),
  );
  return $themes;
}
