<?php

/**
 * @file
 * A small module with high module weight.
 */


/**
 * Implements hook_form_alter().
 *
 */
function sites_last_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node'])) {
    if ($form['type']['#value'] . '_node_form' == $form_id) {
      $form['actions']['submit']['#submit'][] = 'sites_last_node_form_submit';
    }
  }
}

/**
 * Handles submit for node form.
 *
 * Redirect to the subsite when saving a node, to avoid access denied.
 */
function sites_last_node_form_submit($form, &$form_state) {
  if (!empty($form_state['values']['workbench_access'])) {
    $site = SiteController::getSiteByTerm($form_state['values']['workbench_access']);
    if ($site->sid > 1) {
      // Unset destination if page edit always should show the
      // resuting page ( could be configurable pr. user )
      // unset($_GET['destination']);
      $form_state['redirect'] = $site->purl_prefix . '/' . $form_state['redirect'][0];
    }
  }
}