<?php

/**
 * Implements hook_wysiwyg_plugin()
 * for WYSIWYG module
 */
function adapt_ckeditor_widgets_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    // Only do this for ckeditor
    case 'ckeditor':
      return array(
        'textbox' => array(
          'url' => '',
          'path' => drupal_get_path('module', 'adapt_ckeditor_widgets') . '/plugins/textbox',
          'filename' => 'plugin.js',
          'buttons' => array(
            'textbox' => t('Adapt textbox'),
          ),
          'load' => TRUE,
          'internal' => FALSE,
        ),
      );
      break;
  }
}

function adapt_ckeditor_widgets_preprocess_html(&$variables) {
  drupal_add_js(drupal_get_path('module', 'adapt_ckeditor_widgets') . '/js/adapt_ckeditor_widgets.js', array('group' => JS_LIBRARY));
}
