<?php
/**
 * @file
 * atp_data_deployment.features.uuid_features_menu.inc
 */

/**
 * Implements hook_menu_default_uuid_features_menu().
 */
function atp_data_deployment_menu_default_uuid_features_menu() {
  $menu_uuid_links = array();

  // Exported menu link: 004c07fd-c300-4cc7-9874-8eeca0070201
  $menu_uuid_links['004c07fd-c300-4cc7-9874-8eeca0070201'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Resultater & rapporter',
    'options' => array(
      'node_type' => 'section',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'uuid' => '004c07fd-c300-4cc7-9874-8eeca0070201',
    'uuid_path' => 'node/a34caed2-b478-496a-9e16-4ed60706a280',
  );
  // Exported menu link: 08954b4d-8b0f-4e72-84b3-415e1b340bc7
  $menu_uuid_links['08954b4d-8b0f-4e72-84b3-415e1b340bc7'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Kategori B',
    'options' => array(
      'node_type' => 'page',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'uuid' => '08954b4d-8b0f-4e72-84b3-415e1b340bc7',
    'parent_uuid' => 'e50f0574-2730-4e7d-bae3-d3a7edad891e',
    'uuid_path' => 'node/986679d1-ee2b-4d5a-85a4-3373f0aaadac',
  );
  // Exported menu link: 19f485ea-3202-482f-b6b4-7d7305f9d032
  $menu_uuid_links['19f485ea-3202-482f-b6b4-7d7305f9d032'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Kategori C',
    'options' => array(
      'node_type' => 'page',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'uuid' => '19f485ea-3202-482f-b6b4-7d7305f9d032',
    'parent_uuid' => 'e50f0574-2730-4e7d-bae3-d3a7edad891e',
    'uuid_path' => 'node/b176bbfa-7ae3-4217-9842-3f49e5631df2',
  );
  // Exported menu link: 391e308e-e858-4d52-a91c-ee4968fbd491
  $menu_uuid_links['391e308e-e858-4d52-a91c-ee4968fbd491'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Markedsrisiko',
    'options' => array(
      'node_type' => 'page',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'uuid' => '391e308e-e858-4d52-a91c-ee4968fbd491',
    'parent_uuid' => 'ef93402e-dfee-11e3-a989-d1f96a278528',
    'uuid_path' => 'node/dc538c53-463a-4548-9c60-542c078ca68d',
  );
  // Exported menu link: 53cc40ed-2782-48ca-94f6-6987f84679e4
  $menu_uuid_links['53cc40ed-2782-48ca-94f6-6987f84679e4'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Job',
    'options' => array(
      'node_type' => 'section',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'uuid' => '53cc40ed-2782-48ca-94f6-6987f84679e4',
    'uuid_path' => 'node/126c9a15-3172-4e21-9a34-8194fc363ca2',
  );
  // Exported menu link: 6b9ce347-f21c-11e3-a020-080027880ca6
  $menu_uuid_links['6b9ce347-f21c-11e3-a020-080027880ca6'] = array(
    'menu_name' => 'menu-top',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Kontakt',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'uuid' => '6b9ce347-f21c-11e3-a020-080027880ca6',
  );
  // Exported menu link: 74c9bb16-e016-11e3-a989-d1f96a278528
  $menu_uuid_links['74c9bb16-e016-11e3-a989-d1f96a278528'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Dilemma',
    'options' => array(
      'node_type' => 'page',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'uuid' => '74c9bb16-e016-11e3-a989-d1f96a278528',
    'parent_uuid' => 'e50f0574-2730-4e7d-bae3-d3a7edad891e',
    'uuid_path' => 'node/5318a2bf-5d2e-4d11-a674-97050f2bb29e',
  );
  // Exported menu link: 8c1eeee8-7bd4-46ef-a5c7-b87a929fd134
  $menu_uuid_links['8c1eeee8-7bd4-46ef-a5c7-b87a929fd134'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Kategori D',
    'options' => array(
      'node_type' => 'page',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'uuid' => '8c1eeee8-7bd4-46ef-a5c7-b87a929fd134',
    'parent_uuid' => 'e50f0574-2730-4e7d-bae3-d3a7edad891e',
    'uuid_path' => 'node/2da5bce7-e4b3-45cb-9ff1-e9662edddbcd',
  );
  // Exported menu link: 9d1fc520-d3ae-4414-bacd-56e1fabd3b54
  $menu_uuid_links['9d1fc520-d3ae-4414-bacd-56e1fabd3b54'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Om ATP',
    'options' => array(
      'node_type' => 'section',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'uuid' => '9d1fc520-d3ae-4414-bacd-56e1fabd3b54',
    'uuid_path' => 'node/242906e5-3663-4679-9564-399ec3fd5431',
  );
  // Exported menu link: a9609d05-e26f-11e3-8111-080027880ca6
  $menu_uuid_links['a9609d05-e26f-11e3-8111-080027880ca6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'ATP som pensionsforvalter',
    'options' => array(
      'attributes' => array(
        'title' => 'For private og erhverv',
      ),
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'uuid' => 'a9609d05-e26f-11e3-8111-080027880ca6',
  );
  // Exported menu link: a9609ee0-e26f-11e3-8111-080027880ca6
  $menu_uuid_links['a9609ee0-e26f-11e3-8111-080027880ca6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'ATP som investor',
    'options' => array(
      'attributes' => array(
        'title' => 'Bag om Pension',
      ),
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'uuid' => 'a9609ee0-e26f-11e3-8111-080027880ca6',
  );
  // Exported menu link: a960a282-e26f-11e3-8111-080027880ca6
  $menu_uuid_links['a960a282-e26f-11e3-8111-080027880ca6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'ATP som administrator',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'uuid' => 'a960a282-e26f-11e3-8111-080027880ca6',
  );
  // Exported menu link: a960a332-e26f-11e3-8111-080027880ca6
  $menu_uuid_links['a960a332-e26f-11e3-8111-080027880ca6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Info & selvbetjening',
    'options' => array(
      'attributes' => array(
        'title' => 'Bag om ordning og ydelser',
      ),
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'uuid' => 'a960a332-e26f-11e3-8111-080027880ca6',
  );
  // Exported menu link: bbd725b6-ce67-42ed-b9d1-322f36117dd4
  $menu_uuid_links['bbd725b6-ce67-42ed-b9d1-322f36117dd4'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Presse',
    'options' => array(
      'node_type' => 'section',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'uuid' => 'bbd725b6-ce67-42ed-b9d1-322f36117dd4',
    'uuid_path' => 'node/2074d978-c018-4a38-9958-a1319fb23ed1',
  );
  // Exported menu link: c19ad1b7-cda9-4798-bda7-1a43b59d0322
  $menu_uuid_links['c19ad1b7-cda9-4798-bda7-1a43b59d0322'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'I fokus',
    'options' => array(
      'node_type' => 'section',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'uuid' => 'c19ad1b7-cda9-4798-bda7-1a43b59d0322',
    'uuid_path' => 'node/b1f6ffd9-177e-4808-8fb0-73e718679b17',
  );
  // Exported menu link: e50f0574-2730-4e7d-bae3-d3a7edad891e
  $menu_uuid_links['e50f0574-2730-4e7d-bae3-d3a7edad891e'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Samfundsansvar',
    'options' => array(
      'node_type' => 'section',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -49,
    'uuid' => 'e50f0574-2730-4e7d-bae3-d3a7edad891e',
    'uuid_path' => 'node/1b92d8ff-afeb-455f-a1bd-91fe74393f25',
  );
  // Exported menu link: ef93402e-dfee-11e3-a989-d1f96a278528
  $menu_uuid_links['ef93402e-dfee-11e3-a989-d1f96a278528'] = array(
    'menu_name' => 'menu-top',
    'router_path' => 'node/%',
    'link_title' => 'Kategori A',
    'options' => array(
      'node_type' => 'page',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'uuid' => 'ef93402e-dfee-11e3-a989-d1f96a278528',
    'parent_uuid' => 'e50f0574-2730-4e7d-bae3-d3a7edad891e',
    'uuid_path' => 'node/b14112cf-9c19-404f-824e-259762c2a32f',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('ATP som administrator');
  t('ATP som investor');
  t('ATP som pensionsforvalter');
  t('Dilemma');
  t('I fokus');
  t('Info & selvbetjening');
  t('Job');
  t('Kategori A');
  t('Kategori B');
  t('Kategori C');
  t('Kategori D');
  t('Kontakt');
  t('Markedsrisiko');
  t('Om ATP');
  t('Presse');
  t('Resultater & rapporter');
  t('Samfundsansvar');

  return $menu_uuid_links;
}
