<?php
/**
 * @file
 * Utilities and tools for development.
 */

define('ATP_DEV_UUID_FRONTPAGE', '93bfeec1-73bf-4fa4-b971-2666f8f15e0b');

/**
 * Get the node id of the front page node.
 *
 * @return mixed
 *   nid / FALSE
 */
function atp_dev_get_frontpage_nid() {
  $fp = entity_get_id_by_uuid('node', array(ATP_DEV_UUID_FRONTPAGE));
  if (!empty($fp) && !empty($fp[ATP_DEV_UUID_FRONTPAGE])) {
    return (int) $fp[ATP_DEV_UUID_FRONTPAGE];
  }
  return FALSE;
}

/**
 * Setting the frontpage nid.
 */
function atp_dev_update_7001(&$sandbox) {
  module_load_include('module', 'atp_dev');
  $frontpage_path = sprintf('node/%s', atp_dev_get_frontpage_nid());
  watchdog(
    'atp_dev:update',
    t('Setting front page path to %path', array('%path' => $frontpage_path))
  );
  variable_set('site_frontpage', $frontpage_path);
}